### ISSUE TITLE
Iterable basictypes

### ISSUE THREAD

**Issue by msurkovsky** [spirali/pyqit#29]
Is there any reason why haydi's basic types like set/map are not iterable?

**Comment by spirali** [comment]
It is just a missing implementation; feel free to add it.
Btw: The reason why ``__in__`` and ``__getitem__`` is not implemented is documented in the recent version of doc.

**Comment by msurkovsky** [comment]
Ok. I'm not sure currently if I need `__in__` and `__getitem__` methods. If so, I can check these specific types and convert them into python `dict` and `set`. Otherwise I add implementation of iterators.

**Comment by msurkovsky** [comment]
I've implemented the `__iter__` methods for both of these types. It was enough to be accepted by _automatic graph renderer_. I consider the renderer mostly finished. Tomorrow I'm going to prepare a set of test, maybe tune according some other structures and send a version for testing.
